README.md
core/src/main/java/com/pholser/junit/quickcheck/generator/Generator.java
core/src/main/java/com/pholser/junit/quickcheck/generator/GeneratorConfigurationException.java
core/src/main/java/com/pholser/junit/quickcheck/internal/generator/CompositeGenerator.java
core/src/test/java/com/pholser/junit/quickcheck/ComponentizedGeneratorsDoNotPassConfigurationOnToComponentsTest.java
core/src/test/java/com/pholser/junit/quickcheck/MarkedWithSuperfluousConfigurationTest.java
generators/src/test/java/com/pholser/junit/quickcheck/ForAllPrimitiveTheoryParameterTypesTest.java

When generating values for a theory parameter p of type T, annotated with
some set of configuration annotations S, junit-quickcheck used to call
upon all available generators that could produce a T to generate values for
p, silently ignoring the fact that some of those generators might not support
some of the configuration annotations in S.
Now, only those generators that can produce a T *and* support all of the
configuration annotations in S will be called upon thusly.

For #65, filter available generators by config support.

---

core/src/main/java/com/pholser/junit/quickcheck/Property.java
core/src/main/java/com/pholser/junit/quickcheck/internal/ShrinkControl.java
core/src/main/java/com/pholser/junit/quickcheck/runner/PropertyStatement.java
core/src/main/java/com/pholser/junit/quickcheck/runner/Shrinker.java
core/src/test/java/com/pholser/junit/quickcheck/ShrinkingTest.java
core/src/test/java/com/pholser/junit/quickcheck/test/generator/Foo.java

Here is a proposed implementation of #75.  I renamed the property to maxShrinkTime to make it more clear that it only controls shrink time, and increased its granularity to milliseconds.
Let me know what you think.  Any suggestions welcome.

Added shrinking control "maxShrinkTime" for maximum time elapsed

---

core/src/main/java/com/pholser/junit/quickcheck/DisableOnFailingSetHook.java
core/src/main/java/com/pholser/junit/quickcheck/OnFailingSetHook.java
core/src/main/java/com/pholser/junit/quickcheck/Property.java
core/src/main/java/com/pholser/junit/quickcheck/hook/DisableOnFailingSetHook.java
core/src/main/java/com/pholser/junit/quickcheck/internal/ShrinkControl.java
core/src/main/java/com/pholser/junit/quickcheck/runner/PropertyStatement.java
core/src/main/java/com/pholser/junit/quickcheck/runner/PropertyVerifier.java
core/src/main/java/com/pholser/junit/quickcheck/runner/ShrinkNode.java
core/src/main/java/com/pholser/junit/quickcheck/runner/Shrinker.java
core/src/test/java/com/pholser/junit/quickcheck/OnFailingSetHookTest.java

The first patch 1e20ad5 adds the option to execute user-defined code on the minimal counter example.
In the second patch c4d9ad5, there is additionally the option to repeat the failing test with the counter example. For instance, it could be used with a hook like this:
```
public static class RepeatFailingTestForever implements OnFailingSetHook {
@Override
public void handle(Object[] counterExample, Runnable repeatTestOption) {
for (;;) {
System.out.println("Repeating failing test with input: " + Arrays.deepToString(counterExample));
repeatTestOption.run();
try {
Thread.sleep(500);
} catch (InterruptedException e) {
}
}
}
}
```
To install the hook, you have to overwrite the default hook in the propety (which is just a NOOP):
```
@Property(onFailingSet = RepeatFailingTestForever.class)
``` …

Optional hook for debugging failing tests

---

core/src/main/java/com/pholser/junit/quickcheck/internal/generator/PropertyParameterGenerationContext.java
core/src/main/java/com/pholser/junit/quickcheck/runner/PropertyStatement.java
core/src/main/java/com/pholser/junit/quickcheck/runner/PropertyVerifier.java
core/src/main/java/com/pholser/junit/quickcheck/runner/ShrinkNode.java
core/src/main/java/com/pholser/junit/quickcheck/runner/Shrinker.java

This would be a pretty simple way to report seeds by just passing the seeds along with the generated args.
Fixes #92

Report parameter seeds in AssertionErrors

---

core/src/main/java/com/pholser/junit/quickcheck/runner/ShrinkNode.java
core/src/main/java/com/pholser/junit/quickcheck/runner/Shrinker.java
core/src/test/java/com/pholser/junit/quickcheck/ShrinkingTest.java

When a property fails, and shrinking kicks in, the reported assertion error
used to have the shrinking message, but the stack trace of the failure
that caused shrinking to occur. Now, the "top-level" assertion error is
the one raised by the shrinker, its stack trace is preserved, and the
assertion error that caused shrinking to happen in the first place is
embedded as the "cause" of the top-level error. That way, we have more
information about the failure.

For #99, make original failure the cause of shrinking error

---

core/src/main/java/com/pholser/junit/quickcheck/Pair.java
core/src/main/java/com/pholser/junit/quickcheck/generator/Gen.java
core/src/test/java/com/pholser/junit/quickcheck/PairTest.java

The javafx Pair is unavailable in OpenJDK. This hurts Linux users.

For #120, replace javafx.util.Pair with homegrown

---

core/src/main/java/com/pholser/junit/quickcheck/internal/Ranges.java
core/src/main/java/com/pholser/junit/quickcheck/random/SourceOfRandomness.java
core/src/test/java/com/pholser/junit/quickcheck/internal/RangesTest.java

Generating random ints and longs is the major bottleneck
(at least in the execution of my quickcheck tests). So, with this change,
I saw an overall speedup of about 2x-3x.
This is not a patch to add functionality or make the code more readable.
I would recommend to critically measure yourself whether you can reproduce
the speedups. For my workloads, they are significant.
As a second baseline, I also plugged in the implementation found in
ThreadLocalRandom#internalNextLong. At least in my test scenarios,
I did not notice an overall speedup in comparison to my version. I get
about the same overall speedup (2x-3x).
On a microlevel, I would expect the JDK version to be faster and it does not
have the "slow path" that my version has. Overall, it does not seem to make a
significant differences …

Avoid BigInteger computation in Ranges#choose when dealing with longs

---

core/pom.xml
core/src/main/java/com/pholser/junit/quickcheck/runner/JUnitQuickcheck.java
core/src/main/java/com/pholser/junit/quickcheck/runner/JUnitQuickcheckTestClass.java
generators/src/test/java/com/pholser/junit/quickcheck/ComparableWithConsistentEqualsContract.java
generators/src/test/java/com/pholser/junit/quickcheck/ComparatorContract.java
generators/src/test/java/com/pholser/junit/quickcheck/IntegerComparableTest.java
generators/src/test/java/com/pholser/junit/quickcheck/IntegerComparatorTest.java

Needed a correction to javaruntype to handle self-referential generics
bounds (1.3).

For #136, support contract tests via i/f default methods

---

core/pom.xml

ognl 3.1.2 pulled in an old version av javassist that clashes with PowerMock.

pom: Use ognl with modern javassist

---

core/src/main/java/com/pholser/junit/quickcheck/internal/ParameterTypeContext.java
generators/src/test/java/com/pholser/junit/quickcheck/ContractTestWithArrayTypeParameterTest.java

This is a little punt-y, and perhaps corner-case-y to begin with.
At the very least, the minimal test case supplied with the issue now
passes.
Over time, we'll have to decide how or if at all to handle annotations
on type parameters in contract tests.

For #144, handle array types as type parms on contract tests

---

core/src/main/java/com/pholser/junit/quickcheck/internal/Reflection.java

As it is the library cannot be used with Kotlin Annotations to create Annotated Generators as specified here: http://pholser.github.io/junit-quickcheck/site/0.6/usage/configuring.html
If used as it is the library throws a `StackoverflowException` since it doesn't consider the Kotlin Annotations as the ones to be ignored when searching for the annotations recursively.

Added support for Kotlin annotations

---

core/src/main/java/com/pholser/junit/quickcheck/generator/Ctor.java
core/src/main/java/com/pholser/junit/quickcheck/generator/Fields.java
core/src/main/java/com/pholser/junit/quickcheck/generator/Generator.java
core/src/main/java/com/pholser/junit/quickcheck/internal/generator/GeneratorRepository.java
core/src/test/java/com/pholser/junit/quickcheck/PropertyParameterGenerationByConstructorTest.java
core/src/test/java/com/pholser/junit/quickcheck/PropertyParameterGenerationByFieldsTest.java
generators/pom.xml

This will be useful for users that are explicitly manipulating their
own `GeneratorRepository`. These generators already do not get included
in the service loader manifest in junit-quickcheck-core.

For #172, Ctor and Fields now registerable

---

src/site/markdown/usage/shrinking.md

The previous example didn't include some easy pitfalls that I missed when implementing my first shrinks.
Returning more shrinks than necessary wastes time and maxShrinks iterations.

Update shrink example to avoid unnecessary shrinks

---

core/src/main/java/com/pholser/junit/quickcheck/runner/ShrinkNode.java
core/src/test/java/com/pholser/junit/quickcheck/ShrinkingTest.java
core/src/test/java/com/pholser/junit/quickcheck/test/generator/AFooBadShrinks.java
src/site/markdown/usage/shrinking.md

Some "natural" shrinking implementations can lead to retrying the same shrink many times. For example, shrinking a Point (x, y) into:
(x/2, y)
(0, y)
(x, y/2)
(x, 0)
results in many unnecessary shrinks if equals is not checked and one of x or y is much larger than the other.

Ignore shrinks that are equal to "larger"

---

core/src/main/java/com/pholser/junit/quickcheck/runner/PropertyStatement.java
core/src/main/java/com/pholser/junit/quickcheck/runner/PropertyVerifier.java

Some assertion libraries still emit this exception, the parent of the
now-published org.junit.AssumptionViolatedException. To support these
libraries, junit-quickcheck will trap the parent exception.

For #190, trap org.junit.internal.AssumptionViolatedException

---

core/src/main/java/com/pholser/junit/quickcheck/generator/Distinct.java
core/src/main/java/com/pholser/junit/quickcheck/internal/Lists.java
core/src/main/java/com/pholser/junit/quickcheck/internal/generator/ArrayGenerator.java
generators/src/main/java/com/pholser/junit/quickcheck/generator/java/util/CollectionGenerator.java
generators/src/main/java/com/pholser/junit/quickcheck/generator/java/util/MapGenerator.java
generators/src/test/java/com/pholser/junit/quickcheck/DistinctArrayPropertyParameterTypesTest.java
generators/src/test/java/com/pholser/junit/quickcheck/DistinctListPropertyParameterTypesTest.java
generators/src/test/java/com/pholser/junit/quickcheck/DistinctMapPropertyParameterTypesTest.java
generators/src/test/java/com/pholser/junit/quickcheck/DistinctSetPropertyParameterTypesTest.java

This modification enables:
* Generation of array/Collection/Map whose values/elements/keys are distinct from each other
* Strict size constraint on `Set` and `Map` (`@Size` cannot strictly constrain sizes of `Set` and `Map` without distinct value generation)
@pholser, could you take a look?

Enable distinct array/Collection/Map generation (@Distinct)

---

core/src/main/java/com/pholser/junit/quickcheck/generator/Generator.java

The shrinking mechanism discards candidate shrink values that have
equal or lesser "magnitude" than the smallest counterexample found
so far. Generators tell the magnitude of the values they produce.
Collections and other aggregate types have a magnitude that is
a function of the magnitude of their elements.
Prior to this change, if a generator writer did not override
`magnitude()`, then any given output from the generator would have
magnitude zero. This proves problematic when generating collections
of such values, because any list-of-X would have a magnitude of zero,
and no shrinking would occur.
The fix implemented in this change is to change this default
magnitude to one.
Follow-on changes that might be helpful: document some more of the
innards of the shrinking mechanism and how a …

For #205, change Generator.magnitude() to default to 1

---

README.md

Previously it lied and said it was the 0.81 documentation, but it currently is version 0.82 documentation and I think this will change dynamically.

Change documentation link text to be more general

---

src/site/markdown/usage/other-types.md

When using non-static inner classes for generators, `com.pholser.junit.quickcheck.internal.ReflectionException: java.lang.InstantiationException` gets thrown.

Add documentation to warn about edge case

---

core/src/main/java/com/pholser/junit/quickcheck/generator/Fields.java
generators/src/main/java/com/pholser/junit/quickcheck/generator/java/util/LocaleGenerator.java
generators/src/main/java/com/pholser/junit/quickcheck/generator/java/util/RFC4122.java
generators/src/main/java/com/pholser/junit/quickcheck/generator/java/util/TimeZoneGenerator.java
generators/src/main/java/com/pholser/junit/quickcheck/generator/java/util/function/BiPredicateGenerator.java
generators/src/main/java/com/pholser/junit/quickcheck/generator/java/util/function/PredicateGenerator.java
generators/src/main/java/com/pholser/junit/quickcheck/generator/java/util/function/ToDoubleBiFunctionGenerator.java
generators/src/main/java/com/pholser/junit/quickcheck/generator/java/util/function/ToDoubleFunctionGenerator.java
generators/src/main/java/com/pholser/junit/quickcheck/generator/java/util/function/ToIntBiFunctionGenerator.java
generators/src/main/java/com/pholser/junit/quickcheck/generator/java/util/function/ToIntFunctionGenerator.java
generators/src/main/java/com/pholser/junit/quickcheck/generator/java/util/function/ToLongBiFunctionGenerator.java
generators/src/main/java/com/pholser/junit/quickcheck/generator/java/util/function/ToLongFunctionGenerator.java

It takes time to instantiate and configure generator, so it should not be
instantiated inside generate(...) calls.
fixes #238

Avoid repeated computations in #generate() methods

---

LICENSE.txt

Adds the full text of the MIT license to the root directory of the project.
This is a resolution to issue #251.

Add MIT license to the root of the project

---

guava/src/test/java/com/pholser/junit/quickcheck/guava/generator/FunctionPropertyParameterTypesTest.java

Currently, test `arrayOfFunction` fails when run by itself. The test seems to wrongly assert on `SuperShortToExtendsInteger` instead of `ArrayOfFunction`, so it originally only "passes" when run after `superShortToInteger`. This pull request changes the assertion to use `ArrayOfFunction` instead.

Fixing arrayOfFunction test that wrongly asserts on SuperShortToExtendsInteger

---

examples/src/test/java/com/pholser/junit/quickcheck/examples/crypto/SymmetricKeyCryptoPropertiesTest.java

Fixed SymmetricKeyCryptoPropertiesTest.decryptReversesEncrypt
This test was failing when I tried to build project. `plainText` is generated in UTF-8 but new String() depends on default encoding of system. So assertion was failing.
Travis agent default encoding would be `utf-8`. That's why this test passed was passed there.
P.S - Also removed unused imports.

fixed test by converting String in UTF-8 charset

---

core/src/main/java/com/pholser/junit/quickcheck/runner/JUnitQuickcheck.java
core/src/main/java/com/pholser/junit/quickcheck/runner/JUnitQuickcheckTestClass.java
pom.xml

Upgrading to JUnit 4.13 also.
This will prevent the symptom whereby user gets a SecurityError running
on newer JDKs b/c the class invoking the ctor directly previously was
in the same package as FrameworkField (to allow package-private access)
but in a different JAR file.

For #267, invoke FrameworkField ctor reflectively

---

core/src/main/java/com/pholser/junit/quickcheck/internal/ParameterTypeContext.java
core/src/test/java/com/pholser/junit/quickcheck/internal/ReflectionTest.java

ExplicitGroupOfPropertyParameterGeneratorsChosenWithEqualProbabilityTest and ExplicitGroupOfPropertyParameterGeneratorsChosenWithDiscreteProbabilityTest's `producesExpectedRandomValues` test is nondeterministic. When setting up the test, the list of generators is obtained from `ParameterTypeContext#annotate` which uses `Reflection#allAnnotationsByType` to get all of the `From` annotations. However, internally, `Reflection#allAnnotationsByType` uses the `getAnnotationsByType` method which according to posts such as this: https://stackoverflow.com/questions/16756291/is-java-annotation-order-persistent does not guarantee the order the annotations are returned in. As a result, the generators used by these tests could be returned in a different order than expected. The proposed change in …

Fix Nondeterministic Ordering in Tests

---

core/src/test/java/com/pholser/junit/quickcheck/UsualJUnitMachineryOnSubclassPropertyTest.java

The test `com.pholser.junit.quickcheck.UsualJUnitMachineryOnSubclassPropertyTest.expectedOrderingOfMethods` is system-dependent and fails when running on Mac. In addition, it's non-idempotent and fails if run twice in the same JVM, because it pollutes state shared among tests. It may be good to remove the system dependence so that it can be run consistently on every platform.  Furthermore, the state pollution may be removed so that some other tests do not fail in the future due to the shared state polluted by these tests.
`UsualJUnitMachineryOnSubclassPropertyTest.expectedOrderingOfMethods` fails in the following assertion on Mac:
```
assertEquals(resourceAsString("subclass-property-test-expected.txt"), bytesOut.toString());
```
The root cause is that the expected resource string is using …

Fix flakiness in UsualJUnitMachineryOnSubclassPropertyTest

---

core/src/test/java/com/pholser/junit/quickcheck/UsualJUnitMachineryOnTraitBasedPropertyTest.java

The test `com.pholser.junit.quickcheck.UsualJUnitMachineryOnTraitBasedPropertyTest.expectedOrderingOfMethods` is system-dependent and fails when running on Mac. In addition, it's non-idempotent and fails if run twice in the same JVM, because it pollutes state shared among tests. It may be good to remove the system dependence so that it can be run consistently on every platform. Furthermore, the state pollution may be removed so that some other tests do not fail in the future due to the shared state polluted by these tests.
The root cause is similar to what's detailed in https://github.com/pholser/junit-quickcheck/pull/286 .
With the suggested fixes, the test passes(on Mac), and does not pollute the shared state(also passes when run twice in the same JVM).

Fix flakiness in UsualJUnitMachineryOnTraitBasedPropertyTest

---

core/src/test/java/com/pholser/junit/quickcheck/UsualJUnitMachineryOnPropertyBasedTest.java

The test `com.pholser.junit.quickcheck.UsualJUnitMachineryOnPropertyBasedTest.orderingOfStatements` is not idempotent and fails if run twice in the same JVM, because it pollutes state shared among tests. It may be good to clean this state pollution so that some other tests do not fail in the future due to the shared state polluted by this test.
Added a static method `clearLogs()` in `PropertyBasedTests` class to clear the logs. When `UsualJUnitMachineryOnPropertyBasedTest.orderingOfStatements()` finishes, call `PropertyBasedTests.clearLogs()` to clear all the logs.
With the proposed fix, the test does not pollute the shared state (and passes when run twice in the same JVM).

Clear logs after test in UsualJUnitMachineryOnPropertyBasedTest

---

core/src/test/java/com/pholser/junit/quickcheck/UsualJUnitMachineryOnShrinkingPropertyBasedTest.java

The test `com.pholser.junit.quickcheck.UsualJUnitMachineryOnShrinkingPropertyBasedTest.orderingOfStatements` is not idempotent and fails if run twice in the same JVM, because it pollutes state shared among tests. It may be good to clean this state pollution so that some other tests do not fail in the future due to the shared state polluted by this test. 
The root cause and suggest fix are identical  to the ones in https://github.com/pholser/junit-quickcheck/pull/288 .
Added a static method `clearLogs()` in `PropertyBasedTests` class to clear the logs. When `UsualJUnitMachineryOnShrinkingPropertyBasedTest.orderingOfStatements()` finishes, call `PropertyBasedTests.clearLogs()` to clear all the logs.
With the proposed fix, the test does not pollute the shared state (and passes when run twice …

Clear logs in UsualJUnitMachineryOnShrinkingPropertyBasedTest

---

core/src/test/java/com/pholser/junit/quickcheck/SamplingButAlsoIncludingAGivenSetTest.java

The tests
`com.pholser.junit.quickcheck.SamplingButAlsoIncludingAGivenSetTest.primitiveBytes` and
`com.pholser.junit.quickcheck.SamplingButAlsoIncludingAGivenSetTest.wrapperChars`
are not idempotent and fail if run twice in the same JVM, because they pollutes state shared among tests. It may be good to clean this state pollution so that some other tests do not fail in the future due to the shared state polluted by these tests.
**Brief changelog**
Clear the counter `PrimitiveBytes.iterations` at the end of test `primitiveBytes`.
Clear the counter `WrapperChars.iterations` at the end of test `wrapperChars`.
**Verifying this change**
With the proposed fix, the tests do not pollute the shared state (and pass when run twice in the same JVM).

Clear the shared state after some tests

---

generators/src/test/java/com/pholser/junit/quickcheck/PrimitivePropertyParameterTypesTest.java

The test `com.pholser.junit.quickcheck.PrimitivePropertyParameterTypesTest.voidParameter` is not idempotent and fails if run twice in the same JVM, because it pollutes state shared among tests. It may be good to clean this state pollution so that some other tests do not fail in the future due to the shared state polluted by this test.
Reset `VoidParameter.iterations` to 0 at the end of `voidParameter()` test.
With the proposed fix, the test does not pollute the shared state (and passes when run twice in the same JVM).

Reset VoidParameter.iterations after PrimitivePropertyParameterTypesTest.voidParameter() test

---

generators/src/test/java/com/pholser/junit/quickcheck/CallablePropertyParameterTest.java

The test `com.pholser.junit.quickcheck.CallablePropertyParameterTest.callable` is not idempotent and fails if run twice in the same JVM, because it pollutes state shared among tests. It may be good to clean this state pollution so that some other tests do not fail in the future due to the shared state polluted by this test.
Reset `CallableOfInt.iterations` to 0 at the end of `callable()` test.
With the proposed fix, the test does not pollute the shared state (and passes when run twice in the same JVM).

Reset CallableOfInt.iterations after test callable()

---

core/src/test/java/com/pholser/junit/quickcheck/ExhaustingAGivenSetButIncludingAnotherTest.java
core/src/test/java/com/pholser/junit/quickcheck/PropertyParameterConfigurationIsolationTest.java
core/src/test/java/com/pholser/junit/quickcheck/PropertyTupleSampleSizeTest.java
core/src/test/java/com/pholser/junit/quickcheck/SamplingButAlsoIncludingAGivenSetTest.java

This PR is similar to #286 and #294.
1. Failed Tests:
- This PR fixes 26 flaky tests in module `core`, in 4 classes:
```
com.pholser.junit.quickcheck.ExhaustingAGivenSetButIncludingAnotherTest
com.pholser.junit.quickcheck.PropertyParameterConfigurationIsolationTest
com.pholser.junit.quickcheck.PropertyTupleSampleSizeTest
com.pholser.junit.quickcheck.SamplingButAlsoIncludingAGivenSetTest
```
2. Why they fail
- These tests pollute the state shared among tests without clearing `xxx.iterations`. For example, ```com.pholser.junit.quickcheck.ExhaustingAGivenSetButIncludingAnotherTest.manyParameters``` does not clear `ManyParameters.iterations`.
- It may be better to clean state pollutions so that some other tests won't fail in the future due to the shared state polluted by these tests.
3. …

Clean shared state pollution to avoid flaky tests in module core

---

generators/src/test/java/com/pholser/junit/quickcheck/PrimitivePropertyParameterTypesTest.java

This PR is similar to recently opened #357 and previously merged #294 and #295.
1. Failed Tests:
- This PR fixes 2 flaky tests in module `generators`:
```
com.pholser.junit.quickcheck.PrimitivePropertyParameterTypesTest.primitiveBooleanWithAllValues
com.pholser.junit.quickcheck.PrimitivePropertyParameterTypesTest.wrapperBooleanWithAllValues
```
2. Why they fail
- These tests pollute the state shared among tests without clearing `PrimitiveBooleanWithAllValues.values` and `WrapperBooleanWithAllValues.values`
- It may be better to clean state pollutions so that some other tests won't fail in the future due to the shared state polluted by these tests.
3. Reproduce test failures
- Take ```com.pholser.junit.quickcheck.PrimitivePropertyParameterTypesTest.primitiveBooleanWithAllValues``` for …

Clean shared state pollution to avoid flaky tests.

---

core/src/test/java/com/pholser/junit/quickcheck/ComponentizedGeneratorsIsolateConfigurationFromComponentsTest.java
core/src/test/java/com/pholser/junit/quickcheck/EnumPropertyParameterTypesTest.java
core/src/test/java/com/pholser/junit/quickcheck/ExhaustingAGivenSetButIncludingAnotherTest.java
core/src/test/java/com/pholser/junit/quickcheck/ExhaustingAGivenSetTest.java
core/src/test/java/com/pholser/junit/quickcheck/LambdaPropertyParameterTypesTest.java
core/src/test/java/com/pholser/junit/quickcheck/PropertyExhaustiveSampleSizeTest.java
core/src/test/java/com/pholser/junit/quickcheck/SamplingButAlsoIncludingAGivenSetTest.java
core/src/test/java/com/pholser/junit/quickcheck/SamplingOnlyFromAGivenSetTest.java
core/src/test/java/com/pholser/junit/quickcheck/ShrinkingTest.java

This PR is similar to #357 and this PR fixes all remaining cases of pollution that I know of.
1. Failed Tests:
- This PR fixes flaky tests in 9 classes:
```
com.pholser.junit.quickcheck.ComponentizedGeneratorsIsolateConfigurationFromComponentsTest
com.pholser.junit.quickcheck.EnumPropertyParameterTypesTest
com.pholser.junit.quickcheck.ExhaustingAGivenSetButIncludingAnotherTest
com.pholser.junit.quickcheck.ExhaustingAGivenSetTest
com.pholser.junit.quickcheck.LambdaPropertyParameterTypesTest
com.pholser.junit.quickcheck.PropertyExhaustiveSampleSizeTest
com.pholser.junit.quickcheck.SamplingButAlsoIncludingAGivenSetTest
com.pholser.junit.quickcheck.SamplingOnlyFromAGivenSetTest
com.pholser.junit.quickcheck.ShrinkingTest
```
2. Why they fail
- These tests pollute the state shared among tests …

Clear shared pollution to avoid flaky tests

---

.github/workflows/ci.yml

The AdoptOpenJDK has been discontinued since July 2021. When using Zulu you get all the latest updated (TCK Tested) builds for all versions of OpenJDK. I also added major fixed releases where Azul Zulu supports all archived versions.

Using TCK Tested JDK builds of OpenJDK

---

core/src/main/java/com/pholser/junit/quickcheck/internal/Reflection.java

**Overview:**
There is an error detected in the test `com.pholser.junit.quickcheck.generator.java.util.SetOfSuperFloatPropertyParameterTest.verifyInteractionWithRandomness`
The `wildcard ?` super Float helps to generate all Types which Float is a Superclass of, however, in this context, we require to generate all Types which are Superclass of Float (like `Integer`, `Decimal`).
**The fix:**
Use the wildcard `? extends Float` instead of `? super Float`.
All test cases pass after making the change.
Reference : [Stackoverflow question](https://stackoverflow.com/questions/4343202/difference-between-super-t-and-extends-t-in-java)
**Steps to detect and reproduce the error:**
On running the command
```
mvn -pl generators test -Dtest=com.pholser.junit.quickcheck.generator.java.util.SetOfSuperFloatP …
```

Fix SetOfSuperFloatPropertyParameterTest for Super classes of Type Float
